### ISSUE TITLE
Add ability to set width on dialogs for GUI Interfaces or sane auto defaults

### ISSUE THREAD

**Issue by frederickjh** [lunarcloud/script-dialog#8]
Zenity dialogs have  bad habit of making the window very wide if you have a long text string. I like to set the width so that the text wraps on to several lines with a shorter width or easier readability.

To be able to do that one needs to be able to set the **--width=** on the Zenity dialogs. Please consider adding this functionality.

Thanks!
Frederick

**Comment by frederickjh** [comment]
I have changed the title as this also applies to the width of the windows for `dialog`.  To change these I had to edit `script-dialog.sh`.

**Comment by frederickjh** [comment]
@lunarcloud, maybe I am not understanding your code. Can you please explain the `calculateTextDialogSize` function, how it works and the logic behind it?

I am ending up with very small user interface windows.

**Comment by lunarcloud** [comment]
You provide `calculateTextDialogSize  `with a string to test width of.
It runs `updateDialogMaxSize `to make sure the dialog sizes never reach off the edges of the screen.
It calculates size by rows and columns of characters, I beleive.
if the size is greater than the maximum size, it defaults to the maximum size.

These sizes are only ever used for the TUI interfaces.
**The GUI interfaces currently do not have any special size calculations set.**

**Comment by lunarcloud** [comment]
Seems like the size update function never worked due to the way bash functions can't affect the variables outside them.

We should return the 3 values and read them in, something like:

```bash
read -r RECMD_WIDTH RECMD_HEIGHT RECMD_SCROLL <<<$(calculateTextDialogSize "$1")
```

To get this to the GUI (zenity), we should multiply this recommended width/height from their columns & lines values by typical font width, say 12pt ~= 15 pixels.

**Comment by lunarcloud** [comment]
Improved automatic values, and also provided 2 new variables you can use to override.

```bash
ZENITY_HEIGHT=1024 ZENITY_WIDTH=640 displayFile "$HOME/test.log"
```
